sudo: false
dist: trusty

language: cpp
compiler:
  - clang
  - g++

addons:
  apt:
    packages:
      - cmake

script:
  - "mkdir build && cd build"
  - "cmake .."
  - "make"
  - "cd .. && tools/is_formatted.sh"
