sudo: required
dist: trusty

addons:
  apt:
    packages:
      - cmake
      - libgtest-dev

language: cpp

compiler:
  - clang
  - g++

#build gtest
before_install:
  - sudo chown -R /usr/src/gtest/
  - cd /usr/src/gtest/
  - mkdir build && cd build
  - cmake ..
  - sudo cp -a libgtest_main.so libgtest.so /usr/lib/

script:
  - "mkdir build && cd build"
  - "cmake .."
  - "make"
  - "cd .. && tools/is_formatted.sh"
