sudo: required

language: generic
matrix:
  include:
    -
      addons:
        apt:
          packages:
            - g++-6
            - gcc-6
            - libgtest-dev
          sources:
            - ubuntu-toolchain-r-test
      env: "CXX=g++-6 CC=gcc-6"
    -
      addons:
        apt:
          packages:
            - clang-3.8
            - libgtest-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
      env: "CXX=clang++-3.8 CC=clang-3.8"

#build gtest
before_install:
  - cd /usr/src/gtest/
  - sudo mkdir build && cd build
  - sudo cmake .. -DBUILD_SHARED_LIBS=ON
  - sudo make
  - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
  - cd "${TRAVIS_BUILD_DIR}"

script:
  - "mkdir build && cd build"
  - "cmake .."
  - "make"
  - ./ut
  - "cd .. && tools/is_formatted.sh"
