sudo: false

language: cpp
compiler:
  - clang
  - g++

addons:
  apt:
    packages:
      - cmake
      - clang-3.8
      - g++-6

script:
  - "mkdir build && cd build"
  - "cmake .."
  - "make"
  - "cd .. && tools/is_formatted.sh"
