sudo: required
dist: trusty

addons:
  apt:
    packages:
      - cmake
      - libgtest-dev

language: cpp

compiler:
#  - clang
  - g++

#build gtest
before_install:
  - cd /usr/src/gtest/
  - sudo mkdir build && cd build
  - sudo cmake .. -DBUILD_SHARED_LIBS=ON
  - sudo make
  - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
  - cd "${TRAVIS_BUILD_DIR}"

script:
  - "mkdir build && cd build"
  - "cmake .."
  - "make"
  - ./ut
#  - "cd .. && tools/is_formatted.sh"
