sudo: false
dist: trusty

addons:
  apt:
    packages:
      - cmake
      - libboost-all-dev

language: cpp

compiler:
  - clang
  - g++


script:
  - "mkdir build && cd build"
  - "cmake .."
  - "make"
  - "cd .. && tools/is_formatted.sh"
