version: 2
jobs:
  build:
    docker:
      - image: "ubuntu:19.04"
    steps:
      - checkout
      - run:
          name: install build tools
          command: apt-get update && apt-get install -y gcc g++ cmake
      - run:
          name: generate project
          command: mkdir build && cd build && cmake ..
      - run:
          name: build all
          command: cd build && make
      - run:
          name: run application
          command: ./build/minesweeper
      - run:
          name: run unit tests
          command: ./build/ut
      - run:
          name: verify code formatting
          command: ./tools/is_formatted.sh
